export const GET_LANGLOADING_DATA = "GET_LANGLOADING_DATA";
export const GET_LOADING_DATA = "GET_LOADING_DATA";
export const SET_USERS = "SET_USERS";
export const GET_AUTHLOADING_DATA = "GET_AUTHLOADING_DATA";
